org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m
android.useAndroidX=true
android.enableJetifier=true

# Force Flutter's build tool to pass 36 to all plugins
flutter.targetSdkVersion=36
flutter.compileSdkVersion=36
targetSdkVersion=36
compileSdkVersion=36
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
